name: workflowone

on:
  workflow_dispatch:  
#  push

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
         echo "This is workflowone - Job 1"
         sleep 5

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 2
        run: |
         echo "This is workflowone - Job 2"
         sleep 5

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:   
      - name: Step 3
        run: |
         echo "This workflowone - Job 3"
         sleep 5
  job4:
    runs-on: ubuntu-latest
    needs: [job2,job3]
    steps:     
      - name: Step 4
        run: echo "This is workflowone - Job 4"
