name: workflowTwo

on:
  workflow_dispatch:
      
  pull_request:
 

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
         echo "This is workflowTwo - Job 1"
          sleep 30 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is workflowTwo - Job 2"
